### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ghost** [jeroensmeets/mastodon-app#101] opened 2017-07-18 08:58 UTC
Hello,

I want to translate this app into german.
Where I can find the strings?

Thanks

**Comment by jeroensmeets** [comment] 2017-07-22 15:13
Thank you for your offer! The code is not ready for translations yet. Is it ok if I add your name to the list of people who have offered their help?

**Comment by jeroensmeets** [comment] 2017-07-22 15:15
Duplicate of #35 .

**Closed as completed by jeroensmeets** 2017-07-22 15:15 UTC

**Comment by ghost** [comment] 2017-07-22 15:23
Yes do it
Thanks

Am 22. Juli 2017 17:13:26 MESZ schrieb Jeroen Smeets <notifications@github.com>:
>Thank you for your offer! The code is not ready for translations yet.
>Is it ok if I add your name to the list of people who have offered
>their help?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jeroensmeets/mastodon-app/issues/101#issuecomment-317190049

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
